spring:
  application:
    name: ms-rutaexpress-report
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
      group-id: report
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8084

---
spring:
  config:
    activate:
      on-profile: secure
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
          audience: ${AZURE_CLIENT_ID}
