spring:
  application:
    name: ms-rutaexpress-report
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
      group-id: report
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8084
